# Generated by Django 2.2.4 on 2019-09-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Task',
        ),
    ]
